services:
  promtail:
    image: grafana/promtail:3.4.3
    restart: unless-stopped
    network_mode: host
    user: root
    command:
      - -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - promtail_positions:/var/lib/promtail

volumes:
  promtail_positions:
