import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import openapiTS, { astToString } from 'openapi-typescript';
import prettier from 'prettier';
import ts from 'typescript';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const url = process.argv[2];

if (!url) {
  console.error('Error: Please provide an OpenAPI JSON URL.');
  process.exit(1);
}

async function generate() {
  console.log(`Fetching and transforming schema from: ${url}`);

  try {
    const ast = await openapiTS(url, {
      // Transform format: "binary" to TypeScript "Blob" type
      transform(schemaObject) {
        if (schemaObject.format === 'binary') {
          return ts.factory.createTypeReferenceNode(
            schemaObject.nullable ? 'Blob | null' : 'Blob',
          );
        }
      },
    });

    const rawContents = astToString(ast);
    const outputPath = path.resolve(__dirname, '../src/api/schema.ts');

    const prettierConfig = await prettier.resolveConfig(outputPath);
    const formattedContents = await prettier.format(rawContents, {
      ...prettierConfig,
      parser: 'typescript',
    });

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(
      outputPath,
      `/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n${formattedContents}`,
    );

    console.log(`Schema successfully generated at: ${outputPath}`);
  } catch (error) {
    console.error('Failed to generate schema:', error);
    process.exit(1);
  }
}

generate();
