global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: broccoli-profiling

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["10.104.0.15:9090"]

  - job_name: broccoli-server
    metrics_path: /metrics
    file_sd_configs:
      - files: ["/etc/prometheus/targets/server.json"]

  - job_name: broccoli-worker
    metrics_path: /metrics
    file_sd_configs:
      - files: ["/etc/prometheus/targets/worker.json"]

  - job_name: node
    file_sd_configs:
      - files: ["/etc/prometheus/targets/node.json"]

  - job_name: cadvisor
    file_sd_configs:
      - files: ["/etc/prometheus/targets/cadvisor.json"]

  - job_name: postgres-exporter
    file_sd_configs:
      - files: ["/etc/prometheus/targets/postgres.json"]

  - job_name: redis-exporter
    file_sd_configs:
      - files: ["/etc/prometheus/targets/redis.json"]

  - job_name: seaweedfs
    file_sd_configs:
      - files: ["/etc/prometheus/targets/seaweedfs.json"]

  - job_name: caddy
    file_sd_configs:
      - files: ["/etc/prometheus/targets/caddy.json"]
