import './index.css';
import './App.css';

import { ApiClientProvider } from '@broccoli/sdk/api';
import { I18nProvider } from '@broccoli/sdk/i18n';
import { PluginRegistryProvider } from '@broccoli/sdk/plugin';
import { SidebarProvider } from '@broccoli/sdk/sidebar';
import { ThemeProvider } from '@broccoli/sdk/theme';
import { QueryClientProvider } from '@tanstack/react-query';
import { useEffect } from 'react';
import { Links, Meta, Outlet, Scripts, ScrollRestoration } from 'react-router';
import sharedDepsMap from 'virtual:shared-deps-map';

import { AppLayout } from '@/components/AppLayout';
import { AuthProvider } from '@/contexts/AuthProvider';
import { ContestProvider } from '@/contexts/contest-context';
import { en } from '@/lib/i18n/en';
import { queryClient } from '@/lib/query-client';

import { appConfig } from './config';
// Import plugins
import * as AmazingButtonPlugin from './plugins/amazing-button';
import * as AnalyticsPlugin from './plugins/analytics-plugin';
import * as ContestCountdownPlugin from './plugins/contest-countdown-plugin';
// import * as KeyboardShortcutsPlugin from './plugins/keyboard-shortcuts-plugin';
import * as LocaleSwitcherPlugin from './plugins/locale-switcher-plugin';
import * as NotificationPlugin from './plugins/notification-plugin';
import * as RankingChartsPlugin from './plugins/ranking-charts-plugin';
import * as ThemePlugin from './plugins/theme-plugin';

const plugins = [
  ThemePlugin,
  NotificationPlugin,
  AnalyticsPlugin,
  AmazingButtonPlugin,
  // KeyboardShortcutsPlugin,
  RankingChartsPlugin,
  LocaleSwitcherPlugin,
  ContestCountdownPlugin,
];

export function Layout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    document.documentElement.style.opacity = '';
  }, []);

  return (
    <html
      lang={
        typeof window !== 'undefined'
          ? (localStorage.getItem('broccoli-locale') ?? 'en')
          : 'en'
      }
      suppressHydrationWarning
    >
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Import map for dynamically loaded plugins. Must precede all module scripts.
            Maps bare specifiers (react, etc.) to the host app's module URLs so
            plugins loaded from the backend share the same instances.
            Generated by the shared-deps Vite plugin (virtual:shared-deps-map).
            Content is a build-time constant with no user input — safe from XSS. */}
        {Object.keys(sharedDepsMap).length > 0 && (
          <script
            type="importmap"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({ imports: sharedDepsMap }),
            }}
          />
        )}
        <Meta />
        <Links />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem('theme');if(!t)t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.classList.add(t);var l=localStorage.getItem('broccoli-locale');if(l&&l!=='en')document.documentElement.style.opacity='0'})()`,
          }}
        />
      </head>
      <body>
        <QueryClientProvider client={queryClient}>
          <ApiClientProvider
            baseUrl={appConfig.api.baseUrl}
            authTokenKey={appConfig.api.authTokenKey}
          >
            <I18nProvider defaultLocale="en" coreI18n={{ en }}>
              <ThemeProvider defaultTheme="light" storageKey="theme">
                <AuthProvider>
                  <ContestProvider>
                    <SidebarProvider
                      defaultState="expanded"
                      storageKey="sidebar-state"
                    >
                      <PluginRegistryProvider
                        backendUrl={appConfig.plugin.backendUrl}
                        pluginModules={plugins}
                      >
                        <AppLayout>{children}</AppLayout>
                      </PluginRegistryProvider>
                    </SidebarProvider>
                  </ContestProvider>
                </AuthProvider>
              </ThemeProvider>
            </I18nProvider>
          </ApiClientProvider>
        </QueryClientProvider>
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function Root() {
  return <Outlet />;
}
