import '@/App.css';

import { LOCALE_STORAGE_KEY } from '@broccoli/web-sdk/i18n';
import { THEME_STORAGE_KEY } from '@broccoli/web-sdk/theme';
import { useEffect } from 'react';
import { Links, Meta, Outlet, Scripts, ScrollRestoration } from 'react-router';
import sharedDepsMap from 'virtual:shared-deps-map';

import { ErrorReporter } from '@/components/error-reporter';
import { reportError, reportVitals } from '@/lib/telemetry';

export function Layout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    document.documentElement.style.opacity = '';
  }, []);

  useEffect(() => {
    reportVitals();
  }, []);

  useEffect(() => {
    const onUnhandledRejection = (event: PromiseRejectionEvent) => {
      reportError({
        message: event.reason?.message ?? String(event.reason),
        stack: event.reason?.stack,
      });
    };
    window.addEventListener('unhandledrejection', onUnhandledRejection);

    const onError = (event: ErrorEvent) => {
      reportError({
        message: event.message,
        stack: event.error?.stack,
        url: event.filename
          ? `${event.filename}:${event.lineno}:${event.colno}`
          : undefined,
      });
    };
    window.addEventListener('error', onError);

    return () => {
      window.removeEventListener('unhandledrejection', onUnhandledRejection);
      window.removeEventListener('error', onError);
    };
  }, []);

  return (
    <html
      lang={
        typeof window !== 'undefined'
          ? (localStorage.getItem(LOCALE_STORAGE_KEY) ?? 'en')
          : 'en'
      }
      suppressHydrationWarning
    >
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Import map for dynamically loaded plugins. Must precede all module scripts.
            Maps bare specifiers (react, etc.) to the host app's module URLs so
            plugins loaded from the backend share the same instances.
            Generated by the shared-deps Vite plugin (virtual:shared-deps-map).
            Content is a build-time constant with no user input — safe from XSS. */}
        {Object.keys(sharedDepsMap).length > 0 && (
          <script
            type="importmap"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({ imports: sharedDepsMap }),
            }}
          />
        )}
        <Meta />
        <Links />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem('${THEME_STORAGE_KEY}');if(!t)t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.classList.add(t);var l=localStorage.getItem('${LOCALE_STORAGE_KEY}');if(l&&l!=='en')document.documentElement.style.opacity='0'})()`,
          }}
        />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function Root() {
  return (
    <ErrorReporter>
      <Outlet />
    </ErrorReporter>
  );
}
